irc:
  server: irc.oftc.net
  nick: DorsalFunBot
  user: DorsalFunBot

channels:
- "#dorsal-fun"

modules:
  - name: lightbotactions
    class: LightbotActions
    action: light
  - name: fun
    class: Fun
    action: fun
  - name: help
    class: Help
    action: help
  - name: music
    class: Music
    action: music
  - name: crazy
    class: Crazy
    action: crazy
